Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 200
Layout/LineLength:
  Max: 100
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**.*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'bin/**.*'
    - 'config/**.*'
    - 'config/**/*'
    - 'lib/tasks/**.*'
    - "Gemfile"
    - "Rakefile"
    - "**.md"
    - "**.ico"
    - "**.apib"
    - "**.ru"
    - "**.rake"
    - "**.json"
    - "**.png"
Style/StringLiterals:
  Enabled: false
